In [1]:
import pandas as pd
import numpy as np

## Importing Data and Cleaning it

In [36]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [37]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [38]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

Preprocessing Data

In [39]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

Splitting the Data into Train-Test Set

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


Scaling the data

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [47]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ..., 
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Building the ANN

In [48]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Initializing the ANN

In [55]:
classifier=Sequential()

Adding Input layer

In [56]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

Adding first hidden layer

In [57]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

Adding output layer

In [58]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

Compiling The ANN

In [59]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

Fitting the ANN to the training set

In [60]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 8s 1ms/step - loss: 0.4862 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 5s 685us/step - loss: 0.4294 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 6s 703us/step - loss: 0.4240 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 6s 745us/step - loss: 0.4196 - acc: 0.8146
Epoch 5/100
8000/8000 [==============================] - 6s 742us/step - loss: 0.4168 - acc: 0.8264
Epoch 6/100
8000/8000 [==============================] - 6s 758us/step - loss: 0.4151 - acc: 0.8269
Epoch 7/100
8000/8000 [==============================] - 6s 728us/step - loss: 0.4136 - acc: 0.8285
Epoch 8/100
8000/8000 [==============================] - 6s 724us/step - loss: 0.4124 - acc: 0.8311
Epoch 9/100
8000/8000 [==============================] - 6s 727us/step - loss: 0.4109 - acc: 0.8312
Epoch 10/100
8000/8000 [==============================] - 6s 714us/step - loss: 0.4106 - acc: 0.8344
E

8000/8000 [==============================] - 4s 519us/step - loss: 0.4000 - acc: 0.8335
Epoch 82/100
8000/8000 [==============================] - 3s 368us/step - loss: 0.4004 - acc: 0.8350
Epoch 83/100
8000/8000 [==============================] - 3s 422us/step - loss: 0.4001 - acc: 0.8359
Epoch 84/100
8000/8000 [==============================] - 4s 458us/step - loss: 0.4000 - acc: 0.8340
Epoch 85/100
8000/8000 [==============================] - 3s 415us/step - loss: 0.4000 - acc: 0.8345
Epoch 86/100
8000/8000 [==============================] - 3s 424us/step - loss: 0.4004 - acc: 0.8356
Epoch 87/100
8000/8000 [==============================] - 3s 389us/step - loss: 0.4003 - acc: 0.8349
Epoch 88/100
8000/8000 [==============================] - 4s 439us/step - loss: 0.4001 - acc: 0.8341
Epoch 89/100
8000/8000 [==============================] - 3s 413us/step - loss: 0.4000 - acc: 0.8339
Epoch 90/100
8000/8000 [==============================] - 3s 403us/step - loss: 0.4004 - acc: 0.8350
Epo

# # Making Predictions and Evaluating the Model

Predicting the Test result

In [62]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred > 0.5)

Making the confusion matrix

In [63]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [64]:
cm

array([[1548,   47],
       [ 269,  136]], dtype=int64)